name: Deploy Website
on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Building
      run: |
        npm install
        npm run prod
    - name: Deploying
      run: |
        DIRECTORY=/var/www/fh.snipcola.com
        SITE_DIRECTORY=./api
        rm -rf $DIRECTORY/*
        mv $SITE_DIRECTORY/* $DIRECTORY