name: Deploy
on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Installing Dependencies
      run: npm install
    - name: Building Site
      run: npm run build
    - name: Deploying Site
      run: |
        rm -rf ./site/public/dist
    - name: Deploying Proxy
      run: |
        pm2 delete fh-proxy || true
        pm2 start npm --name fh-proxy -- proxy
        pm2 save --force