name: Deploy
on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Building Site
      run: |
        npm install
        npm run build
    - name: Deploying Site
      run: |
        DIRECTORY=/var/www/fh.snipcola.com
        SITE_DIRECTORY=./site/public
        rm -rf $DIRECTORY/*
        rm -rf $SITE_DIRECTORY/dist
        mv $SITE_DIRECTORY/* $DIRECTORY
    - name: Deploying Proxy
      run: |
        DIRECTORY=/var/www/node/fh-proxy.snipcola.com
        PROXY_DIRECTORY=./api
        PM2_NAME=fh-proxy
        pm2 delete $PM2_NAME || true
        shopt -s extglob
        rm -rf $DIRECTORY/*!(.env)
        mv $PROXY_DIRECTORY/* $DIRECTORY
        pm2 start node --name $PM2_NAME -- $DIRECTORY
        pm2 save --force